### ISSUE TITLE
Issue: 400606 Mumbai Pincode - Seasonal Hyd products visible

### ISSUE THREAD

**Issue by mayurjeevamrut** [mohangudey/mohangudey.github.io#71]
Issue: 400606 Mumbai Pincode - Seasonal Hyd products visible.

**Comment by NimishDukhande** [comment]
Currently there no Seasonal Hyderabad products visible on our website for 400606 pin-code, so closing the issue

![issue resolved](https://user-images.githubusercontent.com/117175909/199693621-ebbcdf3f-ae60-43dc-841e-6d1a81d62be2.jpg)
